version: '3'

services:
  web:
    build: dev-docker/.
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
      - cache
      - postgres
      - es8
    command: >
      sh -c "python manage.py migrate sites &&
      python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: "mongo:4.4"
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  cache:
    image: "redis:latest"
    ports:
      - "6379:6379"

  node:
    image: "node:latest"
    working_dir: /app
    volumes:
      - .:/app
    command: sh dev-docker/node-entrypoint.sh
    ports:
      - "3000:3000"
  es8:
    image: "elasticsearch:8.8.2"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node

  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sefaria
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/sefaria_data

volumes:
  mongo-data:
  postgres-data:
