# NB: This assumes an already-functioning mongo instance.
# Parameters:
# MONGO_HOST: Mongo hostname
# SANDBOX_NAME: The name of the table created by this job
---
{{- if and (eq .Values.sandbox "true") .Values.restore.cleanup  }}
apiVersion: batch/v1
kind: Job
metadata:
  name: destroy-mongo-{{ .Values.deployEnv }}
  labels:
    deployEnv: {{ .Values.deployEnv | quote }}
    {{- include "sefaria.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-delete
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "10"
spec:
  template:
    spec:
      containers:
      - name: destroy-mongo-{{ .Values.deployEnv }}
        image: mongo:4.4
        envFrom:
          - secretRef:
              name: {{ .Values.secrets.localSettings.ref }}
          - configMapRef:
              name: local-settings-{{ .Values.deployEnv }}
          - secretRef:
              name: {{ template "sefaria.secrets.mongoCredentials" . }}
          - secretRef:
              name: local-settings-secrets-{{ .Values.deployEnv }}
              optional: true
        command: ["/script/destroy-mongo.sh"]
        volumeMounts:
        - name: script
          mountPath: /script
      restartPolicy: Never
      volumes:
      - name: script
        configMap:
          name: destroy-mongo-{{ .Values.deployEnv }}
          defaultMode: 0755
  ttlSecondsAfterFinished: 432000
{{- end }}
