{{- if .Values.secrets.mongoCredentials.data }}
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials-{{ .Values.deployEnv }}
  labels:
    deployEnv: "{{ .Values.deployEnv }}"
    {{- include "sefaria.labels" . | nindent 4 }}
type: Opaque
stringData: {{ .Values.secrets.mongoCredentials.data | toYaml | nindent 2 }}
{{- end }}
